# Generated by Django 4.2.11 on 2025-07-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the cabinet member', max_length=200)),
                ('role', models.CharField(help_text='Position or role in the cabinet (e.g., President, Secretary)', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Contact email (optional)', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=15, null=True)),
                ('image', models.ImageField(blank=True, help_text='Profile photo of the cabinet member', null=True, upload_to='cabinet/')),
                ('bio', models.TextField(blank=True, help_text='Brief biography or description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date the member was added')),
            ],
            options={
                'verbose_name_plural': 'Cabinet Members',
                'ordering': ['role', 'name'],
            },
        ),
    ]
