# Generated by Django 5.2.4 on 2025-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('BIT', 'Bachelor of Information Technology'), ('DCIT', 'Diploma in Computer Information Technology'), ('CSC', 'Computer Science')], help_text='Select the course type', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the course content')),
            ],
        ),
    ]
